// web/src/components/form/select-input.tsx
import { component$, QwikFocusEvent, type PropFunction, type QwikChangeEvent } from '@builder.io/qwik';
import type { database_SelectOption } from '~/openapi';

type SelectInputProps = {
  name: string;
  label?: string;
  value: string | undefined;
  error: string;
  required?: boolean;
  ref: PropFunction<(element: Element) => void>;
  onInput$: PropFunction<(event: Event, element: HTMLSelectElement) => void>;
  onChange$: PropFunction<(event: QwikChangeEvent<HTMLSelectElement>, element: HTMLSelectElement) => void>;
  onBlur$: PropFunction<(event: QwikFocusEvent<HTMLSelectElement>, element: HTMLSelectElement) => void>;
  options: database_SelectOption[];
};

export default component$(({ label, error, options, ...props }: SelectInputProps) => {
  const { name, required } = props;
  return (
    <div class="form-control w-full">
      <label class="label">
        <span class="label-text">
          {label} {required && <span>*</span>}
        </span>
      </label>
      <select class="select select-bordered" {...props} id={name} aria-invalid={!!error} aria-errormessage={`${name}-error`}>
        {options.map(({ value, name }) => (
          <option key={value} value={value} selected={value === props.value}>
            {name}
          </option>
        ))}
      </select>
      <label class="label">
        {error && (
          <span id={`${name}-error`} class="label-text-alt text-error">
            {error}
          </span>
        )}
      </label>
    </div>
  );
});

// web/src/components/form/SelectInput.vue
<script setup lang="ts">
import type { database_SelectOption } from '@/openapi';

const props = defineProps<{ title: string; modelValue: number; options: database_SelectOption[]; errors?: any[] }>();
const emit = defineEmits(['update:modelValue']);
</script>

<template>
  <div class="form-control w-full">
    <label class="label">
      <span class="label-text">{{ title }}</span>
    </label>
    <select
      class="select select-bordered w-full"
      :value.number="props.modelValue"
      @input="emit('update:modelValue', parseInt(($event.target as HTMLInputElement)?.value))"
    >
      <option v-for="option in options" :key="option.value" :value="option.value">{{ option.name }}</option>
    </select>
    <label class="label">
      <span class="label-text-alt select-text">
        <span v-for="error in errors" :key="error.$uid" class="text-error">{{ error.$message }}<br /></span>
      </span>
    </label>
  </div>
</template>
