// web/src/components/jobs/job-link.tsx
import type { PropFunction } from '@builder.io/qwik';
import { component$ } from '@builder.io/qwik';
import { useLocation } from '@builder.io/qwik-city';
import type { database_Job } from '~/openapi';
import NavLink from '../nav/nav-link';

export default component$((props: { job: database_Job; onClick$: PropFunction<() => void> }) => {
  const jobIcon = () => {
    if (props.job.svg_icon) {
      return props.job.svg_icon;
    }
    return props.job.description.charAt(0);
  };

  const loc = useLocation();
  const isActive = (job: database_Job) => {
    return loc.params.id == '' + job.id;
  };

  return (
    <>
      <NavLink
        name={props.job.description}
        extra={props.job.local_directory}
        link={'/jobs/' + props.job.id}
        onClick$={props.onClick$}
        active={isActive(props.job)}
        icon={jobIcon()}
        status="test"
        bg="bg-primary"
        text="text-primary-content"
      />
    </>
  );
});

// web/src/components/jobs/JobLink.vue
<script setup lang="ts">
import type { database_Job } from '@/openapi';
import NavLink from '../ui/NavLink.vue';
import { computed } from 'vue';
import { useRoute } from 'vue-router';

const route = useRoute();
const props = defineProps<{
  job: database_Job;
}>();
const emit = defineEmits(['click']);

const isActive = computed(() => route.params.id === '' + props.job);

const jobIcon = () => {
  if (props.job.svg_icon) {
    return props.job.svg_icon;
  }
  return props.job.description.charAt(0);
};
</script>

<template>
  <NavLink
    @click="emit('click')"
    :name="job.description"
    :extra="job.local_directory"
    :link="{ name: 'jobs', params: { id: job.id } }"
    :active="isActive"
    :icon="jobIcon()"
    status="test"
    background="bg-primary"
    text="text-primary-content"
  />
</template>
